name: Trivy SCA Scan   # <-- Workflow Name

on:
  push:
  pull_request:

jobs:
  trivy-sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare ZAP workspace
        run: |
          mkdir -p ${{ github.workspace }}/zap-reports
          chmod 777 ${{ github.workspace }}/zap-reports
      
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: https://juice-shop.herokuapp.com
          workdir: ${{ github.workspace }}/zap-reports
          cmd_options: "-a"
