name: Trivy SCA Scan   # <-- Workflow Name

on:
  push:

jobs:
  trivy-sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4


      - name: Prepare ZAP workspace
        run: |
          mkdir -p ${{ github.workspace }}/zap-reports
          chmod 777 ${{ github.workspace }}/zap-reports
      
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: https://juice-shop.herokuapp.com
          workdir: ${{ github.workspace }}/zap-reports
          cmd_options: "-a"
          fail_action: true
          rules_file_name: zap-rules.conf


      - name: zap-dast-report-${{ github.run_id }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            zap_report.html
            zap_report.json
            
      - name: Publish ZAP Report link
        if: always()
        run: |
          echo "## 🔐 DAST Report (OWASP ZAP)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The OWASP ZAP HTML report has been generated and uploaded as a workflow artifact." >> $GITHUB_STEP_SUMMARY
          echo "Download the artifact **zap-dast-report** and open \`zap_report.html\` in a browser to review the results." >> $GITHUB_STEP_SUMMARY
          


      - name: Publish ZAP Summary
        if: always()
        run: |
          echo "## 🔐 DAST Report (OWASP ZAP)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      
          if [ ! -f zap_report.json ]; then
            echo "⚠️ No ZAP report found." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
      
          HIGH=$(jq '[.site[].alerts[] | select(.riskdesc | startswith("High"))] | length' zap_report.json)
          MEDIUM=$(jq '[.site[].alerts[] | select(.riskdesc | startswith("Medium"))] | length' zap_report.json)
          LOW=$(jq '[.site[].alerts[] | select(.riskdesc | startswith("Low"))] | length' zap_report.json)
          INFO=$(jq '[.site[].alerts[] | select(.riskdesc | startswith("Informational"))] | length' zap_report.json)
      
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| 🔴 High | $HIGH |" >> $GITHUB_STEP_SUMMARY
          echo "| 🟠 Medium | $MEDIUM |" >> $GITHUB_STEP_SUMMARY
          echo "| 🟡 Low | $LOW |" >> $GITHUB_STEP_SUMMARY
          echo "| ℹ️ Info | $INFO |" >> $GITHUB_STEP_SUMMARY
      
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📄 Download **zap-dast-report** artifact for full HTML report." >> $GITHUB_STEP_SUMMARY
      
      

