name: 'Trivy SCA Scan'
on:
  push:
  pull_request:

jobs:
  trivy-sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Trivy SCA Scan Action
        id: trivy
        uses: ./.github/actions/trivy-sca   
        with:
          scanners:  "vuln"
          severity:  "HIGH,CRITICAL"
          version:   "0.69.3"
          skip_dirs: "venv,.venv,.tox,.eggs,build,dist,__pycache__"

      - name: Upload trivy-results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.txt

    - name: Comment Trivy results on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: trivy-results.txt

